version: "3.9"  # optional since v1.27.0
services:
  nft-predict:
    container_name: nft-predict
    build: .
    tty: true
    environment:
      ### Configuration settings required by test_cli.py:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      AWS_SECRET_ACCESS_KEY: minio
      AWS_ACCESS_KEY_ID: minio123
      ACCESS_KEY: minio
      SECRET_KEY: minio123
      S3_HOST: minio
      S3_PORT: 9000
    volumes:
      - logvolume01:/var/log
    depends_on:
      - minio
  minio:
    container_name: nft-minio
    image: minio/minio:RELEASE.2021-03-26T00-00-41Z
    volumes:
      - ./data:/data
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  logvolume01: {}
