name: Test and Release

on:
  push:

jobs:

  deploy-packages:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist

      - name: Display directory structure of downloaded files
        run: ls -lR

      - name: Deploy packages
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: "datacube-core-deployment"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-2" # optional: defaults to us-east-1
          SOURCE_DIR: "dist" # optional: defaults to entire repository
          DEST_DIR: "nrt-predict"
